name: Security Scan & ECS Connection Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: uba-ds-validator
  ECS_CLUSTER: uba-ds-cluster
  ECS_SERVICE: uba-validator-service

jobs:
  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for dependency review

      # Docker Image Security Scan (with relaxed severity)
      - name: Scan with Anchore
        uses: anchore/scan-action@v3
        with:
          image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
          fail-build: false
          severity-cutoff: critical  # Changed from 'high' to 'critical'

      # Infrastructure Security Scan
      - name: Terraform Security Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          quiet: true
          skip_check: CKV_AWS_8,CKV_AWS_107  # Example skips for non-critical rules

      # Dependency Scanning (only on PRs)
      - name: Dependency Check
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@v2
        with:
          base-ref: ${{ github.base_ref }}  # Explicitly set for PRs
          head-ref: ${{ github.head_ref }}

  test-ecs-connection:
    name: Test ECS Connection
    needs: security-scan
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Check ECS Cluster Status
        run: |
          STATUS=$(aws ecs describe-clusters \
            --clusters ${{ env.ECS_CLUSTER }} \
            --query 'clusters[0].status' \
            --output text)
          
          if [ "$STATUS" != "ACTIVE" ]; then
            echo "::error::Cluster is not active (Status: $STATUS)"
            exit 1
          fi
          echo "Cluster status: $STATUS"

      - name: Verify Service Health
        run: |
          SERVICE=$(aws ecs describe-services \
            --cluster ${{ env.ECS_CLUSTER }} \
            --services ${{ env.ECS_SERVICE }} \
            --query 'services[0]')
          
          STATUS=$(jq -r '.status' <<< "$SERVICE")
          DESIRED=$(jq -r '.desiredCount' <<< "$SERVICE")
          RUNNING=$(jq -r '.runningCount' <<< "$SERVICE")
          
          if [ "$STATUS" != "ACTIVE" ] || [ "$RUNNING" -lt "$DESIRED" ]; then
            echo "::error::Service unhealthy (Status: $STATUS, Running: $RUNNING/$DESIRED)"
            exit 1
          fi
          echo "Service healthy (Running: $RUNNING/$DESIRED)"
